default:
  data_prep_outputs_path: "/outputs"
  asset_impact_data_path: "/inputs"
  factset_data_path: "/inputs"
  masterdata_ownership_filename: ""
  masterdata_debt_filename: ""
  ar_company_id__factset_entity_id_filename: ""
  factset_financial_data_filename: ""
  factset_entity_info_filename: ""
  factset_entity_financing_data_filename: ""
  factset_fund_data_filename: ""
  factset_isin_to_fund_table_filename: ""
  factset_iss_emissions_data_filename: ""
  factset_issue_code_bridge_filename: ""
  factset_industry_map_bridge_filename: ""
  factset_manual_pacta_sector_override_filename: ""
  update_currencies: TRUE
  export_sqlite_files: TRUE
  export_archives: TRUE
  imf_quarter_timestamp: "2021-Q4"
  pacta_financial_timestamp: "2021Q4"
  market_share_target_reference_year: 2021
  time_horizon: 5
  scenario_sources_list: ["ETP2020", "GECO2021", "IPR2021", "ISF2021", "WEO2021"]
  sector_list: ["Automotive", "Power", "Fossil Fuels", "Oil&Gas", "Coal"]
  other_sector_list: ["Steel", "Aviation", "Cement"]
  zero_emission_factor_techs: ["Electric", "HydroCap", "NuclearCap", "RenewablesCap"]
  green_techs: ["FuelCell", "Electric", "Hybrid", "RenewablesCap", "HydroCap", "NuclearCap", "FuelCell_HDV", "Electric_HDV", "Hybrid_HDV"]
  scenario_raw_data_to_include: ["etp_2020", "geco_2021", "ipr_2021", "isf_2021", "weo_2021"]
  tech_exclude: ["OtherCap", "OtherFF", "Coking Plant", "Sintering Plant", "Direct Or Smelting Reduction Plant", "Pelletizing Plant", "Grinding Plant", "Passenger / Freight"]
  scenario_geographies_list: ["Global", "NonOECD", "OECD"]
  global_aggregate_scenario_sources_list: ["ETP2020", "GECO2021", "IPR2021", "ISF2021", "WEO2021"]
  global_aggregate_sector_list: ["Power"]


2021Q4:
  masterdata_ownership_filename: "2023-06-05_AI_RMI Bespoke_Company Data Products_masterdata_ownership_2021q4.csv"
  masterdata_debt_filename: "2023-06-05_AI_RMI Bespoke_Company Data Products_masterdata_debt_2021q4.csv"
  ar_company_id__factset_entity_id_filename: "2022-08-17_rmi_ar_fs_id_bridge_2021q4.csv"
  factset_financial_data_filename: ""
  factset_entity_info_filename: ""
  factset_entity_financing_data_filename: ""
  factset_fund_data_filename: ""
  factset_isin_to_fund_table_filename: ""
  factset_iss_emissions_data_filename: ""
  factset_issue_code_bridge_filename: ""
  factset_industry_map_bridge_filename: ""
  factset_manual_pacta_sector_override_filename: ""
  imf_quarter_timestamp: "2021-Q4"
  pacta_financial_timestamp: "2021Q4"
  market_share_target_reference_year: 2021
  scenario_sources_list: ["ETP2020", "GECO2021", "IPR2021", "ISF2021", "WEO2021"]
  sector_list: ["Automotive", "Power", "Fossil Fuels", "Oil&Gas", "Coal"]
  other_sector_list: ["Steel", "Aviation", "Cement"]
  zero_emission_factor_techs: ["Electric", "HydroCap", "NuclearCap", "RenewablesCap"]
  green_techs: ["FuelCell", "Electric", "Hybrid", "RenewablesCap", "HydroCap", "NuclearCap", "FuelCell_HDV", "Electric_HDV", "Hybrid_HDV"]
  scenario_raw_data_to_include: ["etp_2020", "geco_2021", "ipr_2021", "isf_2021", "weo_2021"]
  tech_exclude: ["OtherCap", "OtherFF", "Coking Plant", "Sintering Plant", "Direct Or Smelting Reduction Plant", "Pelletizing Plant", "Grinding Plant", "Passenger / Freight"]
  scenario_geographies_list: ["Global", "NonOECD", "OECD"]
  global_aggregate_scenario_sources_list: ["ETP2020", "GECO2021", "IPR2021", "ISF2021", "WEO2021"]
  global_aggregate_sector_list: ["Power"]

2021Q4_dev_vm:
  inherits: 2021Q4

2021Q4_dev_local:
  inherits: 2021Q4

2021Q4_prod_vm:
  inherits: 2021Q4

2021Q4_sqlite:
  inherits: 2021Q4
  export_sqlite_files: TRUE


2022Q2:
  masterdata_ownership_filename: "2022-08-30_rmi_masterdata_ownership_2022q2.csv"
  masterdata_debt_filename: "2022-10-03_rmi_masterdata_debt_2022q2.csv"
  ar_company_id__factset_entity_id_filename: "2022-08-17_rmi_ar_fs_id_bridge_2021q4.csv"
  factset_financial_data_filename: ""
  factset_entity_info_filename: ""
  factset_entity_financing_data_filename: ""
  factset_fund_data_filename: ""
  factset_isin_to_fund_table_filename: ""
  factset_iss_emissions_data_filename: ""
  factset_issue_code_bridge_filename: ""
  factset_industry_map_bridge_filename: ""
  factset_manual_pacta_sector_override_filename: ""
  imf_quarter_timestamp: "2022-Q2"
  pacta_financial_timestamp: "2022Q2"
  market_share_target_reference_year: 2022
  scenario_sources_list: ["ETP2020", "GECO2021", "IPR2021", "ISF2021", "WEO2021"]
  sector_list: ["Automotive", "Power", "Fossil Fuels", "Oil&Gas", "Coal"]
  other_sector_list: ["Steel", "Aviation", "Cement"]
  zero_emission_factor_techs: ["Electric", "HydroCap", "NuclearCap", "RenewablesCap"]
  green_techs: ["FuelCell", "Electric", "Hybrid", "RenewablesCap", "HydroCap", "NuclearCap", "FuelCell_HDV", "Electric_HDV", "Hybrid_HDV"]
  scenario_raw_data_to_include: ["etp_2020", "geco_2021", "ipr_2021", "isf_2021", "weo_2021"]
  tech_exclude: ["OtherCap", "OtherFF", "Coking Plant", "Sintering Plant", "Direct Or Smelting Reduction Plant", "Pelletizing Plant", "Grinding Plant", "Passenger / Freight"]
  scenario_geographies_list: ["Global", "NonOECD", "OECD"]
  global_aggregate_scenario_sources_list: ["ETP2020", "GECO2021", "IPR2021", "ISF2021", "WEO2021"]
  global_aggregate_sector_list: ["Power"]


2022Q4:
  masterdata_ownership_filename: "2023-06-18_AI_RMI Bespoke_Company Data Products_masterdata_ownership_2022Q4.csv"
  masterdata_debt_filename: "2023-06-18_AI_RMI Bespoke_Company Data Products_masterdata_debt_2022Q4.csv"
  ar_company_id__factset_entity_id_filename: "2023-02-15_AI_RMI_Bespoke_Company_Data_Products_Company_ID_List_2022Q4.csv"
  factset_financial_data_filename: "timestamp-20221231T000000Z_pulled-20240207T161053Z_factset_financial_data.rds"
  factset_entity_info_filename: "timestamp-20221231T000000Z_pulled-20240207T161053Z_factset_entity_info.rds"
  factset_entity_financing_data_filename: "timestamp-20221231T000000Z_pulled-20240207T161053Z_factset_entity_financing_data.rds"
  factset_fund_data_filename: "timestamp-20221231T000000Z_pulled-20240207T161053Z_factset_fund_data.rds"
  factset_isin_to_fund_table_filename: "timestamp-20221231T000000Z_pulled-20240207T161053Z_factset_isin_to_fund_table.rds"
  factset_iss_emissions_data_filename: "timestamp-20221231T000000Z_pulled-20240207T161053Z_factset_iss_emissions.rds"
  factset_issue_code_bridge_filename: "test-from-fds-test-20240207-03-postgres_factset_issue_code_bridge.rds"
  factset_industry_map_bridge_filename: "timestamp-20230123T000000Z_pulled-20000101T000001_factset_industry_map_bridge.rds"
  factset_manual_pacta_sector_override_filename: "timestamp-20230123T000000Z_pulled-20000101T000002_factset_manual_sector_override.rds"
  imf_quarter_timestamp: "2022-Q4"
  pacta_financial_timestamp: "2022Q4"
  market_share_target_reference_year: 2022
  scenario_sources_list: ["GECO2022", "ISF2021", "WEO2022"]
  scenario_raw_data_to_include: ["geco_2022", "isf_2021", "weo_2022"]
  global_aggregate_scenario_sources_list: ["WEO2022"]


desktop:
  inherits: 2022Q4
  data_prep_outputs_path: "./outputs"
  asset_impact_data_path: "./ai_inputs"
  factset_data_path: "./factset_inputs"
