version: "3.2"

services:
  data_prep:
    build:
      context: .
    environment:
      - LOG_LEVEL=TRACE
    volumes:
      - type: bind
        source: ${HOST_FACTSET_EXTRACTED_PATH}
        target: /mnt/factset-extracted
      - type: bind
        source: ${HOST_ASSET_IMPACT_PATH}
        target: /mnt/asset-impact
      - type: bind
        source: ${HOST_OUTPUTS_PATH}
        target: /outputs
