version: "3"

services:
  dataprep:
    build:
      context: .
      secrets:
        - GITHUB_PAT
        - R_DATABASE_USER
        - R_DATABASE_PASSWORD
    volumes:
      - /Users/cjrmi/github/pacta.data.preparation/inputs:/home/shiny/inputs
      - /Users/cjrmi/github/pacta.data.preparation/outputs:/home/shiny/outputs
    environment:
      - R_CONFIG_ACTIVE=2021Q4_dev_vm

secrets:
  GITHUB_PAT:
    file: ./.GITHUB_PAT
  R_DATABASE_USER:
    file: ./.R_DATABASE_USER
  R_DATABASE_PASSWORD:
    file: ./.R_DATABASE_PASSWORD
