version: "3.2"

services:
  data_prep:
    build:
      context: .
    volumes:
      - type: bind
        source: ${HOST_INPUTS_PATH}
        target: /inputs
      - type: bind
        source: ${HOST_OUTPUTS_PATH}
        target: /mnt/outputs
