version: "3"

secrets:
  GITHUB_PAT:
    file: .GITHUB_PAT

services:
  data_prep:
    build:
      context: .
      secrets: GITHUB_PAT
    volumes:
      - /inputs:/home/shiny/inputs
      - /outputs:/home/shiny/outputs
    environment:
      - R_CONFIG_ACTIVE=2021Q4_dev_vm
