version: "3.2"

services:
  workflow.data.preparation_aci:
    build:
      context: ..
      dockerfile: ACI/Dockerfile.ACI
      secrets:
        - github_pat
    volumes:
      - type: bind
        source: ./inputs/factset-extracted
        target: /mnt/factset-extracted
      - type: bind
        source: ./inputs/rawdata
        target: /mnt/rawdata
      - type: bind
        source: ./outputs
        target: /outputs

secrets:
  github_pat:
    file: ./github_pat.txt
