version: "3.2"

services:
  workflow.data.preparation_aci:
    stdin_open: true
    tty: true
    command: ["sh"]
    build:
      context: ..
      dockerfile: ACI/Dockerfile.ACI
      secrets:
        - github_pat
    environment:
      LOG_LEVEL: TRACE
      R_CONFIG_ACTIVE: 2022Q4_CICD
    volumes:
      - type: bind
        source: ./dataprep_inputs
        target: /mnt/dataprep_inputs
      - type: bind
        source: ./inputs/factset-extracted
        target: /mnt/factset-extracted
      - type: bind
        source: ./inputs/rawdata
        target: /mnt/rawdata
      - type: bind
        source: ./outputs
        target: /mnt/outputs

secrets:
  github_pat:
    file: ./github_pat.txt
