name: Adds all new issues and PRs to appropriate projects

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    branches: [main]
    types:
      - opened

jobs:
  add-to-tm-project:
    name: Add issue/PR to Transition Monitor project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/RMI-PACTA/projects/8
          github-token: ${{ secrets.PAT_ADD_ISSUES_TO_PROJECT }}
  
  add-to-maintainer-project:
    name: Add issue/PR to @cjyetman's maintainer project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/orgs/RMI-PACTA/projects/13
          github-token: ${{ secrets.PAT_ADD_ISSUES_TO_PROJECT }}
